export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SELECT_EXERCISE = 'SELECT_EXERCISE';
export const SAVE_EXERCISE = 'SAVE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';